--------------------------------------------------------
--  DDL for Table ESTADO_POLIZA
--------------------------------------------------------

  CREATE TABLE "TALLER_EJB"."ESTADO_POLIZA" 
   (	"ID_ESTADO" NUMBER(3,0), 
	"NOM_ESTADO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_FILES" ;
--------------------------------------------------------
--  DDL for Index ESTADOPOLIZA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TALLER_EJB"."ESTADOPOLIZA_PK" ON "TALLER_EJB"."ESTADO_POLIZA" ("ID_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_FILES" ;
--------------------------------------------------------
--  Constraints for Table ESTADO_POLIZA
--------------------------------------------------------

  ALTER TABLE "TALLER_EJB"."ESTADO_POLIZA" MODIFY ("ID_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "TALLER_EJB"."ESTADO_POLIZA" MODIFY ("NOM_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "TALLER_EJB"."ESTADO_POLIZA" ADD CONSTRAINT "ESTADOPOLIZA_PK" PRIMARY KEY ("ID_ESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_FILES"  ENABLE;
--------------------------------------------------------
--  DDL for Trigger ESTADOPOLIZA_TRG
--------------------------------------------------------

CREATE OR REPLACE TRIGGER "TALLER_EJB"."ESTADOPOLIZA_TRG" 
BEFORE INSERT ON ESTADO_POLIZA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_ESTADO IS NULL THEN
      SELECT ESTADOPOLIZA_SEQ.NEXTVAL INTO :NEW.ID_ESTADO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TALLER_EJB"."ESTADOPOLIZA_TRG" ENABLE;

--------------------------------------------------------
--  DDL for Table RAMOS
--------------------------------------------------------

  CREATE TABLE "TALLER_EJB"."RAMOS" 
   (	"ID" NUMBER(3,0), 
	"NOM_RAMO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_FILES" ;

   COMMENT ON TABLE "TALLER_EJB"."RAMOS"  IS 'AQUI VAMOS A GUARDAR TODOS LOS RAMOS';
--------------------------------------------------------
--  DDL for Index RAMOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TALLER_EJB"."RAMOS_PK" ON "TALLER_EJB"."RAMOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_FILES" ;
--------------------------------------------------------
--  Constraints for Table RAMOS
--------------------------------------------------------

  ALTER TABLE "TALLER_EJB"."RAMOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TALLER_EJB"."RAMOS" MODIFY ("NOM_RAMO" NOT NULL ENABLE);
  ALTER TABLE "TALLER_EJB"."RAMOS" ADD CONSTRAINT "RAMOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_FILES"  ENABLE;
--------------------------------------------------------
--  DDL for Trigger RAMOS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TALLER_EJB"."RAMOS_TRG" 
BEFORE INSERT ON RAMOS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT RAMOS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TALLER_EJB"."RAMOS_TRG" ENABLE;

--------------------------------------------------------
--  CREADO LA TABLA DE ASEGURADOS
--------------------------------------------------------

  CREATE TABLE "TALLER_EJB"."ASEGURADO" 
   (	"ID_ASEGURADO" NUMBER(18,0), 
	"NRO_DOCUMENTO" VARCHAR2(20 BYTE), 
	"NOMBRE_COMPLETO" VARCHAR2(80 BYTE), 
	"FEC_NACIMIENTO" DATE, 
	"FEC_ALTA" DATE, 
	"FEC_BAJA" DATE, 
	"TIPO_ASEGURADO" CHAR(1 BYTE), 
	"TIPO_DOCUMENTO" CHAR(1 BYTE), 
	"TIPO_SEXO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_FILES" ;

   COMMENT ON COLUMN "TALLER_EJB"."ASEGURADO"."TIPO_ASEGURADO" IS '(J) JURIDICO, (N) NATURAL';
--------------------------------------------------------
--  DDL for Index ASEGURADOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TALLER_EJB"."ASEGURADOS_PK" ON "TALLER_EJB"."ASEGURADO" ("ID_ASEGURADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_FILES" ;
--------------------------------------------------------
--  Constraints for Table ASEGURADO
--------------------------------------------------------

  ALTER TABLE "TALLER_EJB"."ASEGURADO" MODIFY ("ID_ASEGURADO" NOT NULL ENABLE);
  ALTER TABLE "TALLER_EJB"."ASEGURADO" MODIFY ("NRO_DOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "TALLER_EJB"."ASEGURADO" MODIFY ("NOMBRE_COMPLETO" NOT NULL ENABLE);
  ALTER TABLE "TALLER_EJB"."ASEGURADO" MODIFY ("TIPO_ASEGURADO" NOT NULL ENABLE);
  ALTER TABLE "TALLER_EJB"."ASEGURADO" MODIFY ("TIPO_DOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "TALLER_EJB"."ASEGURADO" MODIFY ("TIPO_SEXO" NOT NULL ENABLE);
  ALTER TABLE "TALLER_EJB"."ASEGURADO" ADD CONSTRAINT "ASEGURADOS_PK" PRIMARY KEY ("ID_ASEGURADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_FILES"  ENABLE;
  ALTER TABLE "TALLER_EJB"."ASEGURADO" ADD CONSTRAINT "CK_TIPO_SEXO" CHECK (tipo_sexo in ('F','M')) ENABLE;
  ALTER TABLE "TALLER_EJB"."ASEGURADO" ADD CONSTRAINT "CK_TIPO_ASEGURADO" CHECK (tipo_asegurado in ('J','N')) ENABLE;
  ALTER TABLE "TALLER_EJB"."ASEGURADO" DROP CONSTRAINT "CK_TIPO_DOCUMENTO" ;
  ALTER TABLE "TALLER_EJB"."ASEGURADO" ADD CONSTRAINT "CK_TIPO_DOCUMENTO" CHECK (tipo_documento in ('R','P','I')) ENABLE;
--------------------------------------------------------
--  DDL for Trigger ASEGURADOS_TRG
--------------------------------------------------------

CREATE OR REPLACE TRIGGER "TALLER_EJB"."ASEGURADOS_TRG" 
BEFORE INSERT ON ASEGURADO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_ASEGURADO IS NULL THEN
      SELECT ASEGURADOS_SEQ.NEXTVAL INTO :NEW.ID_ASEGURADO FROM SYS.DUAL;
    END IF;
    IF INSERTING AND :NEW.TIPO_ASEGURADO IS NULL THEN
      SELECT ASEGURADOS_SEQ.NEXTVAL INTO :NEW.TIPO_ASEGURADO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TALLER_EJB"."ASEGURADOS_TRG" ENABLE;

--------------------------------------------------------
--  DDL for Table POLIZAS
--------------------------------------------------------

  CREATE TABLE "TALLER_EJB"."POLIZAS" 
   (	"ID_POLIZA" NUMBER(18,0), 
	"ID_RAMO" NUMBER(3,0), 
	"ID_ASEGURADO" NUMBER(6,0), 
	"FEC_VIG_DESDE" DATE, 
	"FEC_VIG_HASTA" DATE, 
	"ID_ESTADO" NUMBER(3,0), 
	"VALOR_PRIMA" NUMBER(18,2), 
	"NRO_COUTAS" NUMBER(3,0), 
	"SN_EN_PAGOS" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_FILES" ;
--------------------------------------------------------
--  DDL for Index POLIZAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TALLER_EJB"."POLIZAS_PK" ON "TALLER_EJB"."POLIZAS" ("ID_POLIZA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_FILES" ;
--------------------------------------------------------
--  Constraints for Table POLIZAS
--------------------------------------------------------

  ALTER TABLE "TALLER_EJB"."POLIZAS" MODIFY ("ID_POLIZA" NOT NULL ENABLE);
  ALTER TABLE "TALLER_EJB"."POLIZAS" MODIFY ("ID_RAMO" NOT NULL ENABLE);
  ALTER TABLE "TALLER_EJB"."POLIZAS" MODIFY ("ID_ASEGURADO" NOT NULL ENABLE);
  ALTER TABLE "TALLER_EJB"."POLIZAS" MODIFY ("FEC_VIG_DESDE" NOT NULL ENABLE);
  ALTER TABLE "TALLER_EJB"."POLIZAS" MODIFY ("FEC_VIG_HASTA" NOT NULL ENABLE);
  ALTER TABLE "TALLER_EJB"."POLIZAS" MODIFY ("ID_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "TALLER_EJB"."POLIZAS" MODIFY ("VALOR_PRIMA" NOT NULL ENABLE);
  ALTER TABLE "TALLER_EJB"."POLIZAS" MODIFY ("NRO_COUTAS" NOT NULL ENABLE);
  ALTER TABLE "TALLER_EJB"."POLIZAS" MODIFY ("SN_EN_PAGOS" NOT NULL ENABLE);
  ALTER TABLE "TALLER_EJB"."POLIZAS" ADD CONSTRAINT "POLIZAS_PK" PRIMARY KEY ("ID_POLIZA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_FILES"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POLIZAS
--------------------------------------------------------

  ALTER TABLE "TALLER_EJB"."POLIZAS" ADD CONSTRAINT "FK_POLIZAS_ASEGURADO" FOREIGN KEY ("ID_ASEGURADO")
	  REFERENCES "TALLER_EJB"."ASEGURADO" ("ID_ASEGURADO") ENABLE;
  ALTER TABLE "TALLER_EJB"."POLIZAS" ADD CONSTRAINT "FK_POLIZAS_ESTADO_POLIZA" FOREIGN KEY ("ID_ESTADO")
	  REFERENCES "TALLER_EJB"."ESTADO_POLIZA" ("ID_ESTADO") ENABLE;
  ALTER TABLE "TALLER_EJB"."POLIZAS" ADD CONSTRAINT "FK_POLIZAS_RAMOS" FOREIGN KEY ("ID_RAMO")
	  REFERENCES "TALLER_EJB"."RAMOS" ("ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger POLIZAS_TRG
--------------------------------------------------------

CREATE OR REPLACE TRIGGER "TALLER_EJB"."POLIZAS_TRG" 
BEFORE INSERT ON POLIZAS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_POLIZA IS NULL THEN
      SELECT POLIZAS_SEQ.NEXTVAL INTO :NEW.ID_POLIZA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TALLER_EJB"."POLIZAS_TRG" ENABLE;


----------------------------------------------------------------------------------------------------------------------
--  INSERTANDO REGISTROS EN LA TABLA DE ESTADOS DE LA POLIZA
-----------------------------------------------------------------------------------------------------------------------
INSERT INTO ESTADO_POLIZA(NOM_ESTADO) values('VIGENTE');
INSERT INTO ESTADO_POLIZA(NOM_ESTADO) values('CANCELADA');
----------------------------------------------------------------------------------------------------------------------
--  INSERTANDO REGISTROS EN LA TABLA DE RAMOS
-----------------------------------------------------------------------------------------------------------------------
INSERT INTO RAMOS(NOM_RAMO) VALUES('AUTOMOVILES');
INSERT INTO RAMOS(NOM_RAMO) VALUES('GASTOS MEDICOS');
INSERT INTO RAMOS(NOM_RAMO) VALUES('VIDA INDIVIDUAL');
INSERT INTO RAMOS(NOM_RAMO) VALUES('VIDA COLECTIVO');
INSERT INTO RAMOS(NOM_RAMO) VALUES('TRANSPORTE');
INSERT INTO RAMOS(NOM_RAMO) VALUES('MASCOTAS');
INSERT INTO RAMOS(NOM_RAMO) VALUES('AGRICOLA');
----------------------------------------------------------------------------------------------------------------------
--  INSERTANDO REGISTROS EN LA TABLA DE ASEGURADOS
-----------------------------------------------------------------------------------------------------------------------
--1
INSERT INTO ASEGURADO(NRO_DOCUMENTO,NOMBRE_COMPLETO,FEC_NACIMIENTO,FEC_ALTA,FEC_BAJA,TIPO_ASEGURADO,TIPO_DOCUMENTO,TIPO_SEXO) 
VALUES('12345678901','MARTYN LOYD JONES',TO_DATE('27/12/1856','DD/MM/YYYY'),TO_DATE('27/01/2020','DD/MM/YYYY'),NULL,'N','I','M');
--2 
INSERT INTO ASEGURADO(NRO_DOCUMENTO,NOMBRE_COMPLETO,FEC_NACIMIENTO,FEC_ALTA,FEC_BAJA,TIPO_ASEGURADO,TIPO_DOCUMENTO,TIPO_SEXO) 
VALUES('12345678902','JORGE MULLER',TO_DATE('27/12/1856','DD/MM/YYYY'),TO_DATE('27/01/2020','DD/MM/YYYY'),NULL,'N','I','M');
--3
INSERT INTO ASEGURADO(NRO_DOCUMENTO,NOMBRE_COMPLETO,FEC_NACIMIENTO,FEC_ALTA,FEC_BAJA,TIPO_ASEGURADO,TIPO_DOCUMENTO,TIPO_SEXO) 
VALUES('12345678903','ROY HUDSON',TO_DATE('27/12/1856','DD/MM/YYYY'),TO_DATE('27/01/2020','DD/MM/YYYY'),NULL,'N','I','M');
--4
INSERT INTO ASEGURADO(NRO_DOCUMENTO,NOMBRE_COMPLETO,FEC_NACIMIENTO,FEC_ALTA,FEC_BAJA,TIPO_ASEGURADO,TIPO_DOCUMENTO,TIPO_SEXO) 
VALUES('12345678904','KARLOTA MOON',TO_DATE('27/12/1856','DD/MM/YYYY'),TO_DATE('27/01/2020','DD/MM/YYYY'),NULL,'N','I','F');
--5
INSERT INTO ASEGURADO(NRO_DOCUMENTO,NOMBRE_COMPLETO,FEC_NACIMIENTO,FEC_ALTA,FEC_BAJA,TIPO_ASEGURADO,TIPO_DOCUMENTO,TIPO_SEXO) 
VALUES('12345678905','FRIDA CALO',TO_DATE('27/12/1856','DD/MM/YYYY'),TO_DATE('27/01/2020','DD/MM/YYYY'),NULL,'N','I','F');

